tact-lang/tact-language-server

- tsconfig.json
**Attention**
I just turned on new checks, I didn't touch the code in any way and it needs to be fixed
> even stricter typescript checks

- .github/workflows/tests.yml
- package.json
- yarn.lock
Made a test run on `Linux`, `MacOS`.
On `Windows` there was a problem with environment setup, will have to fix it. @i582 will you put an issue on it?
> running tests in CI

- .github/workflows/linter.yml
- .gitignore
- eslint.config.mjs
- package.json
- yarn.lock
Decided that I should separate the steps `basic eslint configuration` and `enabling rules`
Enabling rules will be in the next PRs
issue #4
> first stage of `eslint` implementation

- server/src/compiler/TactCompiler.ts
https://github.com/i582/language-server/issues/23
> Fixed parsing in the function. Now it outputs the full error

- server/src/server.ts
> feat(signature-help): add Signature help for `initOf`

- server/src/e2e/suite/testcases/references/contracts.test
- server/src/psi/Reference.ts
- server/src/psi/Referent.ts
- server/src/server.ts
> feat(references): add find references for `init` function

- server/src/completion/providers/SnippetsCompletionProvider.ts
- server/src/e2e/suite/testcases/completion/constants.test
- server/src/e2e/suite/testcases/completion/contracts.test
- server/src/e2e/suite/testcases/completion/functions.test
- server/src/e2e/suite/testcases/completion/initOf.test
- server/src/e2e/suite/testcases/completion/keywords.test
- server/src/e2e/suite/testcases/completion/return.test
- server/src/e2e/suite/testcases/completion/structs.test
- server/src/e2e/suite/testcases/completion/traits.test
- server/src/e2e/suite/testcases/completion/variables.test
> feat(completion): add `do` snippet

- server/src/completion/providers/TraitOrContractConstantsCompletionProvider.ts
- server/src/e2e/suite/testcases/completion/constants.test
- server/src/e2e/suite/testcases/completion/contracts.test
- server/src/e2e/suite/testcases/completion/traits.test
- server/src/server.ts
> feat(completion): add constant declaration completion in traits and contracts

- server/src/completion/providers/TlbSerializationCompletionProvider.ts
- server/src/documentation/tlb_type_documentation.ts
- server/src/e2e/suite/testcases/documentation/tlb-types.test
- server/src/server.ts
> feat(hover): add documentation for TL-B types

- server/src/completion/providers/MessageMethodCompletionProvider.ts
- server/src/e2e/suite/testcases/completion/constants.test
- server/src/e2e/suite/testcases/completion/contracts.test
- server/src/e2e/suite/testcases/completion/traits.test
> feat(completion): add `external() {}` to completion

- server/src/completion/providers/TopLevelFunctionCompletionProvider.ts
- server/src/e2e/suite/index.ts
- server/src/e2e/suite/testcases/completion/top-level.test
> feat(completion): add `extends mutates fun foo(self: Type) {}` to completion

- server/src/completion/providers/TopLevelCompletionProvider.ts
- server/src/completion/providers/TraitOrContractConstantsCompletionProvider.ts
- server/src/e2e/suite/index.ts
- server/src/e2e/suite/testcases/completion/top-level.test
- server/src/server.ts
> feat(completion): add struct/message/trait/constant declaration completion

- server/src/completion/CompletionContext.ts
- server/src/completion/ReferenceCompletionProcessor.ts
> fix(completion): and add brackets only if they are not there yet

- package.json
- server/src/fift/inlays/collect.ts
- server/src/fift/semantic_tokens/collect.ts
- server/src/inlays/collect.ts
- server/src/inspections/CompilerInspection.ts
- server/src/inspections/EmptyBlockInspection.ts
- server/src/inspections/Inspection.ts
- server/src/inspections/MissedFieldInContractInspection.ts
- server/src/inspections/NotImportedSymbolInspection.ts
- server/src/inspections/StructInitializationInspection.ts
- server/src/inspections/UnusedContractMembersInspection.ts
- server/src/inspections/UnusedImportInspection.ts
- server/src/inspections/UnusedParameterInspection.ts
- server/src/inspections/UnusedVariableInspection.ts
- server/src/lens/collect.ts
- server/src/server.ts
- server/src/utils/settings.ts
> feat(configuration): add configuration for all type hints, code lenses and inspections

- server/src/server.ts
> feat(workspace): show error message if stdlib not found

- server/src/intentions/AddExplicitType.ts
- server/src/intentions/FillAllStructInit.ts
- server/src/server.ts
- server/src/types/BaseTy.ts
- server/src/utils/FileDiff.ts
- server/src/utils/position.ts
Fixes #40
https://github.com/user-attachments/assets/0b55b9ad-94ec-481c-af50-3251c7d8ba30
> feat(intentions): initial intention to fill all/required struct/message fields

- server/src/server.ts
> feat(document-symbols): sort elements by position

- server/src/psi/Decls.ts
- server/src/server.ts
> feat(document-symbols): add imports, init() and message receivers (receive, external, bounced)

- README.md
> documentation: add mention of VSCodium / Cursor / Windsurf in README.md

- .github/workflows/nightly-release.yml
- package.json
> feat(CI): add nightly builds

- server/src/intentions/FillAllStructInit.ts
> fix(intention): don't do anything for "Fill in required fields..." if there are no such fields, or no fields to fill in at all

- server/src/e2e/suite/intentions.test.ts
- server/src/e2e/suite/testcases/intentions/AddFieldInitialization.test
- server/src/intentions/AddFieldInitialization.ts
- server/src/psi/Decls.ts
- server/src/psi/Node.ts
- server/src/server.ts
Fixes #151
https://github.com/user-attachments/assets/2c4c0319-77c2-47f3-b817-115eccd92903
> feat(intention): add initial implementation of intention to initialize field in `init()`

- README.md
- server/src/completion/CompletionContext.ts
- server/src/completion/providers/PostfixCompletionProvider.ts
- server/src/e2e/suite/testcases/completion/fields.test
- server/src/e2e/suite/testcases/completion/functions.test
- server/src/server.ts
https://github.com/user-attachments/assets/6bc2c9a0-3859-4830-889e-f8b4e3985db3
> feat(completion): add initial implementation of postfix completion

- package.json
- webpack.config.js
> fix(vscode-extension): fix Tact file icons

- CHANGELOG.md
- server/src/completion/ReferenceCompletionProcessor.ts
- server/src/e2e/suite/testcases/documentation/functions.test
- server/src/psi/Reference.ts
- stubs/stubs.tact
If something's off, please tell :)
Closes #140
> feat(documentation): add missing functions to `stubs/` and adjust the format to match the rest of other stdlib doc `///` comments

- README.md
> chore: add mention of Open VSX Registry

- server/src/e2e/suite/testcases/inlayHints/initOf.test
- server/src/inlays/collect.ts
> feat(inlay-hints): add parameters hints for `initOf Foo()`

- server/src/completion/CompletionContext.ts
- server/src/e2e/suite/testcases/completion/functions.test
> fix(completion): for functions return type

- server/src/documentation/documentation.ts
- server/src/documentation/receivers_documentation.ts
- server/src/e2e/suite/testcases/documentation/contract-functions.test
> feat(documentation): show use documentation for receiver and init  functions

- CHANGELOG.md
- README.md
> feat(documentation): add installation instructions for Vim 8+

- client/src/build-system.ts
- client/src/extension.ts
- package.json
> feat(vscode): initial support for Blueprint and Tact Template build systems

- server/src/compiler/utils.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/completion/top-level.test
- server/src/e2e/suite/testcases/documentation/require.test
- server/src/inlays/collect.ts
- server/src/server.ts
> feat(documentation): show exit code in hover documentation of `require()`

- package.json
- server/src/inlays/collect.ts
> feat(inlay-hints): show stack info for ASM instruction (disabled by default)

- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/documentation/functions.test
> fix(documentation): fix list rendering

- package.json
- server/src/completion/ReferenceCompletionProcessor.ts
- server/src/server.ts
- server/src/utils/settings.ts
https://github.com/user-attachments/assets/81453b1e-049c-49d0-8bc4-f6c36e788099
Fixes #200
> feat(completion): automatically add necessary imports for symbols from other files

- server/src/completion/ReferenceCompletionProcessor.ts
- server/src/e2e/suite/testcases/completion/initOf.test
- server/src/psi/Decls.ts
> fix(completion): add parameters to contract completion inside `initOf`

- server/src/completion/data/types.ts
- server/src/completion/providers/AsmInstructionCompletionProvider.ts
- server/src/documentation/asm_documentation.ts
- server/src/e2e/suite/testcases/completion/asm.test
- server/src/e2e/suite/testcases/documentation/asm.test
- server/src/inlays/collect.ts
> feat(asm): show hint for top element in stack info, show new styled stack info in doc and completion

- README.md
> chore: change priorities of editors in the README

- package.json
- server/src/documentation/documentation.ts
- server/src/psi/utils.ts
- server/src/semantic_tokens/collect.ts
- server/src/semantic_tokens/comments.ts
- server/src/semantic_tokens/tokens.ts
- server/src/semantic_tokens/utils.ts
- server/src/server.ts
- server/src/utils/settings.ts
- yarn.lock
> feat(highlighting): highlight code in doc comments

- server/src/documentation/documentation.ts
- server/src/foldings/collect.ts
- server/src/semantic_tokens/comments.ts
> feat(foldings): folding of doc comments

- package.json
> feat(vscode): split settings to groups

- package.json
- server/src/completion/CompletionContext.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/completion/constants.test
- server/src/e2e/suite/testcases/completion/contracts.test
- server/src/e2e/suite/testcases/completion/traits.test
- server/src/e2e/suite/testcases/documentation/require.test
- server/src/e2e/suite/testcases/documentation/size-of.test
- server/src/e2e/suite/testcases/documentation/structs.test
- server/src/e2e/suite/testcases/inlayHints/toCell.test
- server/src/inlays/collect.ts
- server/src/intentions/AddExplicitType.ts
- server/src/types/BaseTy.ts
- server/src/utils/settings.ts
> feat(documentation/inlay-hints): show type for struct, messages and `toCell()` calls

- client/src/extension.ts
- server/src/server.ts
> fix(vscode): fix LS run on workspace without an open folder and on non-saved buffers

- eslint.config.mjs
- package.json
- server/src/asm/gas.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/documentation/functions.test
- server/src/e2e/suite/testcases/documentation/require.test
- server/src/e2e/suite/testcases/inlayHints/asm.test
- server/src/e2e/suite/testcases/inlayHints/assembly.test
- server/src/inlays/collect.ts
- server/src/psi/Decls.ts
- server/src/semantic_tokens/collect.ts
- server/src/server.ts
- server/src/utils/settings.ts
> feat(gas): take branching into account for gas calculation

- package.json
> fix(vscode): better wording for `compiler path` setting

- package.json
> fix(vscode): make command names uniform

- README.md
- client/src/build-system.ts
- package.json
> feat(build-system): add a Test task for Blueprint and Tact Template

- server/src/completion/CompletionContext.ts
- server/src/completion/providers/GetterCompletionProvider.ts
> fix(completion): for contract/trait top-level

- server/src/psi/ImportResolver.ts
> fix(resolving): support path with explicit `.tact` extension

- README.md
> chore: add header to readme

- server/src/inspections/Inspection.ts
- server/src/inspections/RewriteInspection.ts
- server/src/server.ts
> feat(inspections): rewrite `context().sender` with `sender()`

- package.json
- server/src/inspections/RewriteInspection.ts
- server/src/psi/Node.ts
> feat(inspections): rewrite `send()` with `message()` or `deploy()`

- README.md
> chore: fix grammar in README.md

- stubs/stubs.tact
> feat(stubs): add doc comments to `fromSlice` and `fromCell` functions

- server/src/semantic_tokens/comments.ts
> fix(semantic-tokens): fix highlighting for some keywords in doc comments

- docs/manual/troubleshooting.md
> fix(manual): fix link to issues

- server/src/indexes/index.ts
- server/src/indexing-root.ts
- server/src/psi/ImportResolver.ts
- server/src/psi/Referent.ts
- server/src/server.ts
> feat(definition): prefer project definitions over stdlib one

- server/src/indexes/index.ts
- server/src/indexing-root.ts
- server/src/psi/File.ts
- server/src/psi/ImportResolver.ts
- server/src/psi/Reference.ts
> feat(resolving): initial implementation of import-based resolving

- server/src/completion/ReferenceCompletionProcessor.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/intentions/AddFieldInitialization.test
- server/src/intentions/AddFieldInitialization.ts
- server/src/psi/Decls.ts
> feat(intentions): support `init(init: Init)` pattern

- client/src/extension.ts
- client/src/utils/package-manager.ts
- package.json
> feat(vscode): add command to run Misti on a project with installation if not installed

- server/src/inspections/DontUseDeployableInspection.ts
- server/src/inspections/DontUseTextReceiversInspection.ts
- server/src/inspections/RewriteInspection.ts
- server/src/toolchain/toolchain.ts
> fix(inspections): run some inspections only on Tact 1.6

- server/src/completion/data/types.ts
- server/src/documentation/asm_documentation.ts
- server/src/e2e/suite/index.ts
- server/src/e2e/suite/testcases/documentation/asm.test
- server/src/fift/documentation/documentation.ts
- server/src/server.ts
> feat(documentation): better documentation for assembly instructions

- package.json
- yarn.lock
`vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead`
more detail:
https://www.npmjs.com/package/vsce
> changed the dependency of `vsce` to `"@vscode/vsce`

- server/src/server.ts
- server/src/toolchain/toolchain.ts
> fix: search of stdlib for new projects, and tact toolchain in tact compiler repo

- server/src/TypeInferer.ts
- server/src/indexes/index.ts
- server/src/psi/Reference.ts
> fix: correctly resolve `sha256` with `String` argument

- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/documentation/basic.test
- server/src/e2e/suite/testcases/documentation/functions.test
> fix(hover): don't process doc comments content

- server/src/inspections/UnusedImportInspection.ts
> fix(inspections): better heuristic for unused imports

- server/src/completion/providers/OverrideCompletionProvider.ts
- server/src/e2e/suite/testcases/completion/traits.test
> fix(completion): don't add all methods to override completion

- server/src/completion/providers/TypeTlbSerializationCompletionProvider.ts
> fix(completion): show TL-B type completion in structs, messages and traits

- package.json
- server/src/compiler/crc32.ts
- server/src/compiler/utils.ts
- server/src/e2e/suite/index.ts
- server/src/e2e/suite/testcases/inlayHints/crc32.test
- server/src/inlays/collect.ts
- server/src/utils/settings.ts
> feat(inlay-hints): show evaluation result for `crc32()` builtin function

- package.json
- server/src/e2e/suite/testcases/inspection/CanBeStandaloneFunctionInspection.test
- server/src/e2e/suite/testcases/inspection/EmptyBlockInspection.test
- server/src/inspections/CanBeStandaloneFunctionInspection.ts
- server/src/inspections/Inspection.ts
- server/src/psi/Decls.ts
- server/src/psi/RecursiveVisitor.ts
- server/src/server.ts
> feat(inspections): add an inspection for a function that does not use contract state and can be made standalone

- package.json
- server/src/e2e/suite/testcases/inspection/UseExplicitStringReceiverInspection.test
- server/src/inspections/Inspection.ts
- server/src/inspections/UseExplicitStringReceiverInspection.ts
- server/src/psi/Decls.ts
- server/src/server.ts
> feat(inspections): add an inspection for fallback string receiver with branching for message text

- package.json
- server/src/server.ts
- server/src/utils/settings.ts
> feat(inlay-hints): setting to disable all inlay-hints at once

- package.json
- server/src/TypeInferer.ts
- server/src/compiler/tlb/tlb.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/documentation/basic.test
- server/src/e2e/suite/testcases/documentation/contracts.test
- server/src/e2e/suite/testcases/documentation/size-of.test
- server/src/e2e/suite/testcases/documentation/structs.test
- server/src/psi/Decls.ts
- server/src/types/BaseTy.ts
- server/src/utils/settings.ts
- yarn.lock
> feat(documentation): show TL-B definition for structs, messages and contracts in documentation

- package.json
- server/src/utils/settings.ts
> feat(documentation): add a setting to disable keyword documentation

- package.json
- server/src/compiler/sha256.ts
- server/src/compiler/tlb/compiler-tlb.ts
- server/src/compiler/tlb/tlb.ts
- server/src/documentation/documentation.ts
- server/src/e2e/suite/testcases/documentation/structs.test
- server/src/e2e/suite/testcases/inlayHints/message.test
- server/src/inlays/collect.ts
- server/src/psi/Decls.ts
- server/src/utils/settings.ts
> feat: show hint with message ID inside message declaration

- server/src/compiler/tlb/tlb.ts
- server/src/e2e/suite/testcases/documentation/basic.test
- server/src/e2e/suite/testcases/documentation/contracts.test
- server/src/psi/Decls.ts
> fix(documentation): show `lazy_deployment_bit` in TL-B for contracts

- package.json
- server/src/e2e/suite/testcases/inlayHints/receivers.test
- server/src/inlays/collect.ts
- server/src/types/BaseTy.ts
- server/src/utils/settings.ts
> feat(inlay-hints): add inlay hint for binary receivers

- docs/manual/features/inspections.md
- server/src/e2e/suite/index.ts
- server/src/e2e/suite/testcases/inspection/Rewrite.test
- server/src/inspections/RewriteInspection.ts
> feat(inspection): add rewrite inspections for `self.forward`, `self.reply`, and `self.notify`

- server/src/documentation/documentation.ts
- stubs/stubs.tact
Fix #567 (see its description for details)
> feat(documentation): re-organize struct and message struct hover info

- server/src/compiler/fmt/cst/cst-helpers.ts
- server/src/compiler/fmt/cst/cst-parser.ts
- server/src/compiler/fmt/formatter/format-expressions.ts
- server/src/compiler/fmt/formatter/format-statements.ts
- server/src/compiler/fmt/formatter/helpers.ts
- server/src/compiler/fmt/test/formatter-test.spec.ts
> chore: port formatter changes from Tact (map literals and augmented assign)

- package.json
> chore: clarify in the description that this is an official extension

- CHANGELOG.md
- docs/manual/features/inspections.md
- package.json
- server/src/e2e/suite/testcases/inspection/ImplicitMessageId.test
- server/src/inspections/ImplicitMessageId.ts
- server/src/inspections/Inspection.ts
> refactor: use `message opcode` instead of `message ID`

- eslint.config.mjs
- server/src/indexes/index.ts
- server/src/indexing-root.ts
- server/src/psi/File.ts
- server/src/psi/ImportResolver.ts
- server/src/psi/Reference.ts
- server/src/server.ts
- server/src/toolchain/toolchain.ts
> fix: fix path resolution for paths with special characters like @ or >

- server/src/e2e/suite/testcases/signatureHelp/functions.test
- server/src/e2e/suite/testcases/signatureHelp/struct.test
- server/src/server.ts
> fix(signature-help): more accurate signature info target selection

- package.json
- server/src/e2e/suite/testcases/inspection/MisspelledKeywordInspection.test
- server/src/inspections/Inspection.ts
- server/src/inspections/MisspelledKeywordInspection.ts
- server/src/server.ts
> feat(inspection): add inspection for misspelled `initOf` and `codeOf`

- server/src/compiler/tlb/tlb.ts
- server/src/e2e/suite/testcases/documentation/basic.test
- server/src/e2e/suite/testcases/documentation/structs.test
- server/src/e2e/suite/testcases/documentation/tlb-types.test
> fix(documentation): fix TL-B type for the optional struct / message field

- server/src/e2e/suite/testcases/rename/fields.test
- server/src/server.ts
> fix(rename): support rename when the whole name is selected

- server/src/psi/Decls.ts
> fix(resolving): search `BaseTrait` only in stdlib

- server/src/compiler/tlb/tlb.ts
- server/src/e2e/suite/testcases/documentation/size-of.test
- server/src/e2e/suite/testcases/documentation/structs.test
> fix(tlb): fix TL-B for fields with "as remaining"

- CONTRIBUTING.md
Fixes #638
Fixes #619
Fixes #588
> feat(dev-docs): add CONTRIBUTING.md

- README-extension.md
> chore: mention LLMs documentation files in README-extension.md

- .prettierignore
- server/src/compiler/fmt/cst/process-comments.ts
- server/src/compiler/fmt/formatter/code-builder.ts
- server/src/compiler/fmt/formatter/format-comments.ts
- server/src/compiler/fmt/formatter/format-declarations.ts
- server/src/compiler/fmt/formatter/format-expressions.ts
- server/src/compiler/fmt/formatter/format-imports.ts
- server/src/compiler/fmt/formatter/format-statements.ts
- server/src/compiler/fmt/formatter/formatter.ts
- server/src/compiler/fmt/formatter/helpers.ts
- server/src/compiler/fmt/test/contracts.spec.ts
- server/src/compiler/fmt/test/fix.spec.ts
- server/src/compiler/fmt/test/formatter-test.spec.ts
- server/src/compiler/fmt/test/helpers.ts
- server/src/compiler/fmt/test/ignore-directives.spec.ts
- server/src/compiler/fmt/test/statement-comments.spec.ts
- server/src/compiler/fmt/test/top-level-comments.spec.ts
> chore: backport formatter fixes

- server/src/completion/data/asm.json
> feat(asm): use latest TVM specification with fixes

- client/src/providers/BocEditorProvider.ts
> fix(vscode): fix .boc file focus issue

- server/src/e2e/suite/testcases/intentions/WrapSelected.test
- server/src/e2e/suite/testcases/references/scopes.test
- server/src/e2e/suite/testcases/resolve/basic.test
- server/src/indexes/index.ts
- server/src/server.ts
Fixes #511
Fixes #515
Fixes #575
> fix: don't run inspections and inlay-hints before full initialization

- server/src/indexes/index.ts
- server/src/inspections/NotImportedSymbolInspection.ts
- server/src/psi/ImportResolver.ts
- server/src/psi/Reference.ts
> fix: take into account an import tree, make "NotImportedSymbolInspection" warning and improved overall performance

- README.md
> chore: add installation via NPM section

- CONTRIBUTING.md
> chore: describe a release process in CONTRIBUTING.md

- package.json
- server/src/e2e/suite/testcases/inspection/CanBeInlineInspection.test
- server/src/inspections/CanBeInlineInspection.ts
- server/src/inspections/CanBeStandaloneFunctionInspection.ts
- server/src/inspections/Inspection.ts
- server/src/inspections/UnusedInspection.ts
- server/src/lens/collect.ts
- server/src/psi/Decls.ts
- server/src/psi/Referent.ts
- server/src/psi/visitor.ts
- server/src/server.ts
> feat(inspections): add `CanBeInline` inspection and optimize find references

- server/src/file-renaming.ts
- server/src/server.ts
> feat(renaming): rename import on file rename or move

- client/src/extension.ts
- client/src/providers/BocDecompilerProvider.ts
> feat(vscode): automatically disassemble BoC file if changed

- package.json
> fix(vscode): remove duplicate command

- README-extension.md
- README.md
- client/src/extension.ts
- docs/manual/features/type-based-search.md
- package.json
- server/src/e2e/suite/search.test.ts
- server/src/e2e/suite/testcases/search/type-based-search.test
- server/src/search/TypeBasedSearch.ts
- server/src/search/TypeSignatureParser.ts
- server/src/search/__tests__/TypeSignatureParser.test.ts
- server/src/server.ts
- shared/src/shared-msgtypes.ts
Fixes #387
https://github.com/user-attachments/assets/884f6cbc-1a85-4d2f-bc0f-3680e7cd20fa
> feat(vscode): type-based search

- README.md
- client/src/extension.ts
- docs/manual/features/toolchain-management.md
- package.json
- server/src/server.ts
- server/src/settings/settings.ts
- server/src/toolchain-manager.ts
> Add flexible toolchain settings
