.editorconfig, package.json
Added a configuration that is as close as possible to the current project.
I have not formatted the current code in any way, this will need to be done in a separate commit and then added to `.git-blame-ignore-revs`. @i582, will you do it?
I also added two commands:
- `format` - to format the code
- `format:check` - to check it in CI
In the future, formatting should be added to the pre-hook (TODO issue).
=> introduced `prettier` to the project.

language-configuration.json
The regex is made in the way that `///` are only auto-inserted if they don't have any non-space characters to the start of the line. That is, they're not placed at the end of the code lines.
As a bonus, I've concealed `/**/` comments. This part is debatable, but generally pushing people towards more `///` seems beneficial, especially if we consider removing the `/**/` comments in some future.
Feel free to disagree :)
Closes #92
=> chore: auto-insertion of `///` and concealment of `/**/` comments

server/src/completion/providers/MessageMethodCompletionProvider.ts, server/src/e2e/suite/testcases/completion/constants.test, server/src/e2e/suite/testcases/completion/contracts.test, server/src/e2e/suite/testcases/completion/traits.test
=> feat(completion): add empty `receiver() {}` to completion

server/src/completion/CompletionContext.ts, server/src/completion/providers/BouncedTypeCompletionProvider.ts, server/src/e2e/suite/testcases/completion/messages.test, server/src/server.ts
=> feat(completion): add `bounced<>` to completion

server/src/completion/providers/MemberFunctionCompletionProvider.ts, server/src/e2e/suite/testcases/completion/constants.test, server/src/e2e/suite/testcases/completion/traits.test
=> feat(completion): add `virtual fun foo() {}` to completion

server/src/completion/ReferenceCompletionProcessor.ts, server/src/e2e/suite/testcases/completion/fields.test, server/src/e2e/suite/testcases/completion/variables.test
=> fix(completion): fix completion of variants with the same name

server/src/completion/CompletionContext.ts, server/src/e2e/suite/testcases/completion/messages.test
=> feat(completion): show only messages in `bounced()` and `external()` receivers

server/src/intentions/AddExplicitType.ts, server/src/intentions/Intention.ts, server/src/server.ts
Fixes #126
https://github.com/user-attachments/assets/0dc28f85-238f-4d4d-834d-18f2ac9ae03d
=> feat(intention): add "Add explicit type" intention

server/src/server.ts
=> feat(signature-help): add signature help for struct/message fields

server/src/documentation/receivers_documentation.ts, server/src/psi/Decls.ts, server/src/server.ts
Fixes #87
Fixes #69
Towards #44
=> feat(hover): add documentation for receivers (`receive`, `bounced`, `external`) and `init()` constructor

package.json, server/src/server.ts, server/src/utils/settings.ts
=> feat(find-usages): add setting for "Find Usages" scope

package.json, syntaxes/tact-markdown-injection.json
=> feat(vscode): add Tact code highlighting inside Markdown code blocks

server/src/completion/ReferenceCompletionProcessor.ts
=> fix(completion): don't add extra `()` in `initOf` completion

server/src/e2e/suite/testcases/completion/methods.test, server/src/e2e/suite/testcases/resolve/methods.test, server/src/psi/Reference.ts
=> fix(resolving/completion): for methods on `T?`

server/src/indexes/index.ts, server/src/inspections/NotImportedSymbolInspection.ts
For example in tests with many actual roots
Fixes #223
Fixes #224
Fixes #144
=> fix(inspections): don't warn on symbols with several declarations

server/src/TypeInferer.ts, server/src/completion/ReferenceCompletionProcessor.ts, server/src/documentation/documentation.ts, server/src/e2e/suite/testcases/completion/fromCell.test, server/src/e2e/suite/testcases/documentation/fromCell.test, server/src/e2e/suite/testcases/resolve/fromCell.test, server/src/e2e/suite/testcases/types/fromCell.test, server/src/psi/Reference.ts, stubs/stubs.tact
=> feat(completion/resolving/documentation): add support for `fromCell` and `fromSlice` methods on structs and messages

client/src/extension.ts, package.json, server/src/server.ts, server/src/toolchain/toolchain.ts, server/src/utils/settings.ts, shared/src/shared-msgtypes.ts
=> feat(compiler): initial compiler integration

stubs/stubs.tact
=> feat(documentation): add missing comptime functions to `stubs.tact`

server/src/documentation/documentation.ts, server/src/e2e/suite/testcases/documentation/basic.test, server/src/e2e/suite/testcases/documentation/contracts.test, server/src/e2e/suite/testcases/documentation/traits.test
=> feat(documentation): show members of trait and contract in hover documentation

.gitignore, server/src/e2e/suite/signatureHelp.test.ts, server/src/e2e/suite/signatures.test.ts, server/src/e2e/suite/testcases/signatures/contract.test, server/src/e2e/suite/testcases/signatures/initOf.test, server/src/e2e/suite/testcases/signatures/map.test, server/src/e2e/suite/testcases/signatures/struct.test, server/src/e2e/suite/testcases/signatures/trait.test
Resolves #211 
Summary:
- Added 21 tests for signatureHelp 
- Basic function helps
- Some structs (also need fix and cover this #252)
- Maps
=> test: Add tests for signatureHelp

server/src/e2e/suite/testcases/completion/methods.test, server/src/e2e/suite/testcases/completion/variables.test, server/src/psi/Decls.ts, server/src/psi/Reference.ts
With auto-insertion of `self.` prefix on select
https://github.com/user-attachments/assets/15a3ac5d-c665-45cc-9593-5e4c938e334c
Fixes #70
=> feat(completion): show `self` type fields/methods in completion list

server/src/inlays/collect.ts
=> fix(inlay-hints): don't show parameters hints for unary functions from stubs

server/src/asm/gas.ts, server/src/inlays/collect.ts, server/src/server.ts, tsconfig.json
- Add tooltip for `as int257` hint for beginners
- Resolve parts of type hints
- Resolve parameter hints
- Insert type hint on double-click
Fixes #285
Fixes #284
Fixes #283
Fixes #282
=> feat(inlay-hints): improve type hints

package.json
=> fix(vscode): use flat settings keys

README.md, docs/manual/troubleshooting.md
=> feat(manual): add troubleshooting.md

.github/workflows/nightly-release.yml
=> feat(ci): add changelog to nightly builds

server/src/e2e/suite/testcases/inlayHints/variables.test, server/src/inlays/collect.ts
=> feat(inlay-hints): don't show an obvious type hint for variable initialized with `Foo.fromCell()`

README.md
And also enhance VSIX-related descriptions a little.
Fix #352 (took some time to test and it indeed works and replaces the default `.sublime-completions` with ones from the LS)
=> chore(documentation): override completions in Sublime Text

server/src/documentation/exit_code_documentation.ts, server/src/e2e/suite/testcases/documentation/exit-codes.test, server/src/server.ts
=> feat(documentation): add exit code documentation

server/src/e2e/suite/testcases/signatureHelp/initOf.test, server/src/server.ts
=> fix: fix signature help for `initOf` for contracts with parameters

client/src/providers/BocDecompilerProvider.ts
=> fix(vscode): don't cache disasm for BoC

docs/manual/features/inlay-hints.md, server/src/e2e/suite/testcases/inlayHints/parameters.test, server/src/inlays/collect.ts
=> feat(inlay-hints): don't show parameter hints for call argument with matching name

server/src/e2e/suite/testcases/inlayHints/toCell.test, server/src/inlays/collect.ts
=> fix(inlay-hints): don't show size hint for `toCellI()` in method chain

server/src/e2e/suite/testcases/references/contracts.test, server/src/indexes/index.ts, server/src/psi/Reference.ts, server/src/psi/Referent.ts
=> feat(resolving): prefer local definition when find definitions

server/src/psi/Referent.ts
=> fix(find-usages): correctly determine whether some reference is a reference to target declaration and not another

README.md
=> feat(documentation): enable semantic tokens and better hover doc highlighting for sublime text

server/src/compiler/utils.ts, server/src/e2e/suite/testcases/inlayHints/ascii.test, server/src/inlays/collect.ts
=> fix(inlay-hints): do not show evaluation result for incorrect `ascii()` usage

server/src/compiler/fmt/formatter/format-structs.ts, server/src/compiler/fmt/test/top-level-comments.spec.ts
Closes #600
Backported one fix from the Tact compiler repo.
=> fix(formatter): trailing comments after the last struct field

.github/workflows/linter.yml, .vscodeignore, README-extension.md, package.json, yarn.lock
- Don't add `*.js.map` files (archive only 900 kb… now!)
- Add special README-extension.md for VS Code extension only
- Bump @vscode/vsce package to 3.0.0
Fixes #613
=> feat(vscode-package): improve VS Code packaging

client/src/extension.ts, package.json, server/src/languages/tact/toolchain/toolchain.ts, server/src/server.ts, shared/src/shared-msgtypes.ts
Fixes #721
```
Tact Toolchain Information:
Version: 1.6.6
Commit: Unknown
Path: /Users/petrmakhnev/jetton/node_modules/.bin/tact
Auto-detected: true
Detection method: node_modules
Platform: darwin
Architecture: arm64
Node.js: v22.14.0
```
=> feat(vscode): show toolchain information on status bar widget hover

server/src/e2e/suite/testcases/completion/fromCell.test, server/src/e2e/suite/testcases/documentation/fromCell.test, server/src/e2e/suite/testcases/resolve/fromCell.test, server/src/e2e/suite/testcases/types/fromCell.test, server/src/languages/tact/TypeInferer.ts, server/src/languages/tact/completion/ReferenceCompletionProcessor.ts, server/src/languages/tact/documentation/documentation.ts, server/src/languages/tact/inlays/index.ts, server/src/languages/tact/psi/Reference.ts
=> feat: support contract `Contract.toCell/toSlice` from Tact 1.6.11 and `Contract.fromCell/fromSlice` from Tact 1.6.12

server/src/languages/tlb/completion/providers/BuiltinTypesCompletionProvider.ts, server/src/languages/tlb/documentation/documentation.ts, server/src/languages/tlb/documentation/index.ts, server/src/languages/tlb/semantic-tokens/index.ts, server/src/server.ts
=> feat(tlb): add hover documentation for declarations and builtin types
